var arrayscalars_8h =
[
    [ "PyBoolScalarObject", "struct_py_bool_scalar_object.html", "struct_py_bool_scalar_object" ],
    [ "PyByteScalarObject", "struct_py_byte_scalar_object.html", "struct_py_byte_scalar_object" ],
    [ "PyShortScalarObject", "struct_py_short_scalar_object.html", "struct_py_short_scalar_object" ],
    [ "PyIntScalarObject", "struct_py_int_scalar_object.html", "struct_py_int_scalar_object" ],
    [ "PyLongScalarObject", "struct_py_long_scalar_object.html", "struct_py_long_scalar_object" ],
    [ "PyLongLongScalarObject", "struct_py_long_long_scalar_object.html", "struct_py_long_long_scalar_object" ],
    [ "PyUByteScalarObject", "struct_py_u_byte_scalar_object.html", "struct_py_u_byte_scalar_object" ],
    [ "PyUShortScalarObject", "struct_py_u_short_scalar_object.html", "struct_py_u_short_scalar_object" ],
    [ "PyUIntScalarObject", "struct_py_u_int_scalar_object.html", "struct_py_u_int_scalar_object" ],
    [ "PyULongScalarObject", "struct_py_u_long_scalar_object.html", "struct_py_u_long_scalar_object" ],
    [ "PyULongLongScalarObject", "struct_py_u_long_long_scalar_object.html", "struct_py_u_long_long_scalar_object" ],
    [ "PyHalfScalarObject", "struct_py_half_scalar_object.html", "struct_py_half_scalar_object" ],
    [ "PyFloatScalarObject", "struct_py_float_scalar_object.html", "struct_py_float_scalar_object" ],
    [ "PyDoubleScalarObject", "struct_py_double_scalar_object.html", "struct_py_double_scalar_object" ],
    [ "PyLongDoubleScalarObject", "struct_py_long_double_scalar_object.html", "struct_py_long_double_scalar_object" ],
    [ "PyCFloatScalarObject", "struct_py_c_float_scalar_object.html", "struct_py_c_float_scalar_object" ],
    [ "PyCDoubleScalarObject", "struct_py_c_double_scalar_object.html", "struct_py_c_double_scalar_object" ],
    [ "PyCLongDoubleScalarObject", "struct_py_c_long_double_scalar_object.html", "struct_py_c_long_double_scalar_object" ],
    [ "PyObjectScalarObject", "struct_py_object_scalar_object.html", "struct_py_object_scalar_object" ],
    [ "PyDatetimeScalarObject", "struct_py_datetime_scalar_object.html", "struct_py_datetime_scalar_object" ],
    [ "PyTimedeltaScalarObject", "struct_py_timedelta_scalar_object.html", "struct_py_timedelta_scalar_object" ],
    [ "PyScalarObject", "struct_py_scalar_object.html", "struct_py_scalar_object" ],
    [ "PyVoidScalarObject", "struct_py_void_scalar_object.html", "struct_py_void_scalar_object" ],
    [ "PyArrayScalar_ASSIGN", "arrayscalars_8h.html#aedfc9907827c0d6665528b001f059aa1", null ],
    [ "PyArrayScalar_False", "arrayscalars_8h.html#a8f5a90e06bde838d9fb08e3c5d034b5c", null ],
    [ "PyArrayScalar_FromLong", "arrayscalars_8h.html#a1a5b3a318042fd1078a71f9deafdf763", null ],
    [ "PyArrayScalar_New", "arrayscalars_8h.html#a950afdff49ca6c709f1fbbd6eaab5a5e", null ],
    [ "PyArrayScalar_RETURN_BOOL_FROM_LONG", "arrayscalars_8h.html#a2ffeb891b237a86327a3cd8215bc7a1e", null ],
    [ "PyArrayScalar_RETURN_FALSE", "arrayscalars_8h.html#ab767b44bf330ccca32d49683476f7696", null ],
    [ "PyArrayScalar_RETURN_TRUE", "arrayscalars_8h.html#a37c05ba0ab6dc8c784795a20d36f9a86", null ],
    [ "PyArrayScalar_True", "arrayscalars_8h.html#a49d7fad5a59ff556d1cc651365193f74", null ],
    [ "PyArrayScalar_VAL", "arrayscalars_8h.html#aad47c08024eb433b78ed0cc303df0334", null ],
    [ "PyStringScalarObject", "arrayscalars_8h.html#af4c38a4452599d0b9822a27af058ab05", null ],
    [ "PyUnicodeScalarObject", "arrayscalars_8h.html#a1e7b6bb7400c25d753a02920e494bef5", null ]
];