var dir_38f8eb51c77f77483516f3c506cbfd19 =
[
    [ "tests", "dir_0c9399fc60ffe5c3695f788b1949f86f.html", "dir_0c9399fc60ffe5c3695f788b1949f86f" ],
    [ "__init__.py", "lib_2____init_____8py.html", "lib_2____init_____8py" ],
    [ "_datasource.py", "__datasource_8py.html", "__datasource_8py" ],
    [ "_iotools.py", "__iotools_8py.html", "__iotools_8py" ],
    [ "_version.py", "__version_8py.html", "__version_8py" ],
    [ "arraypad.py", "arraypad_8py.html", "arraypad_8py" ],
    [ "arraysetops.py", "arraysetops_8py.html", "arraysetops_8py" ],
    [ "arrayterator.py", "arrayterator_8py.html", "arrayterator_8py" ],
    [ "financial.py", "financial_8py.html", "financial_8py" ],
    [ "format.py", "format_8py.html", "format_8py" ],
    [ "function_base.py", "lib_2function__base_8py.html", "lib_2function__base_8py" ],
    [ "histograms.py", "histograms_8py.html", "histograms_8py" ],
    [ "index_tricks.py", "index__tricks_8py.html", "index__tricks_8py" ],
    [ "info.py", "lib_2info_8py.html", "lib_2info_8py" ],
    [ "mixins.py", "mixins_8py.html", "mixins_8py" ],
    [ "nanfunctions.py", "nanfunctions_8py.html", "nanfunctions_8py" ],
    [ "npyio.py", "npyio_8py.html", "npyio_8py" ],
    [ "polynomial.py", "lib_2polynomial_8py.html", "lib_2polynomial_8py" ],
    [ "recfunctions.py", "recfunctions_8py.html", "recfunctions_8py" ],
    [ "scimath.py", "scimath_8py.html", "scimath_8py" ],
    [ "setup.py", "lib_2setup_8py.html", "lib_2setup_8py" ],
    [ "shape_base.py", "lib_2shape__base_8py.html", "lib_2shape__base_8py" ],
    [ "stride_tricks.py", "stride__tricks_8py.html", "stride__tricks_8py" ],
    [ "twodim_base.py", "twodim__base_8py.html", "twodim__base_8py" ],
    [ "type_check.py", "type__check_8py.html", "type__check_8py" ],
    [ "ufunclike.py", "ufunclike_8py.html", "ufunclike_8py" ],
    [ "user_array.py", "user__array_8py.html", "user__array_8py" ],
    [ "utils.py", "lib_2utils_8py.html", "lib_2utils_8py" ]
];