var dir_0c9399fc60ffe5c3695f788b1949f86f =
[
    [ "__init__.py", "lib_2tests_2____init_____8py.html", null ],
    [ "test__datasource.py", "test____datasource_8py.html", "test____datasource_8py" ],
    [ "test__iotools.py", "test____iotools_8py.html", "test____iotools_8py" ],
    [ "test__version.py", "test____version_8py.html", "test____version_8py" ],
    [ "test_arraypad.py", "test__arraypad_8py.html", "test__arraypad_8py" ],
    [ "test_arraysetops.py", "test__arraysetops_8py.html", "test__arraysetops_8py" ],
    [ "test_arrayterator.py", "test__arrayterator_8py.html", "test__arrayterator_8py" ],
    [ "test_financial.py", "test__financial_8py.html", "test__financial_8py" ],
    [ "test_format.py", "test__format_8py.html", "test__format_8py" ],
    [ "test_function_base.py", "lib_2tests_2test__function__base_8py.html", "lib_2tests_2test__function__base_8py" ],
    [ "test_histograms.py", "test__histograms_8py.html", "test__histograms_8py" ],
    [ "test_index_tricks.py", "test__index__tricks_8py.html", "test__index__tricks_8py" ],
    [ "test_io.py", "test__io_8py.html", "test__io_8py" ],
    [ "test_mixins.py", "test__mixins_8py.html", "test__mixins_8py" ],
    [ "test_nanfunctions.py", "test__nanfunctions_8py.html", "test__nanfunctions_8py" ],
    [ "test_packbits.py", "test__packbits_8py.html", "test__packbits_8py" ],
    [ "test_polynomial.py", "lib_2tests_2test__polynomial_8py.html", "lib_2tests_2test__polynomial_8py" ],
    [ "test_recfunctions.py", "test__recfunctions_8py.html", "test__recfunctions_8py" ],
    [ "test_regression.py", "lib_2tests_2test__regression_8py.html", "lib_2tests_2test__regression_8py" ],
    [ "test_shape_base.py", "lib_2tests_2test__shape__base_8py.html", "lib_2tests_2test__shape__base_8py" ],
    [ "test_stride_tricks.py", "test__stride__tricks_8py.html", "test__stride__tricks_8py" ],
    [ "test_twodim_base.py", "test__twodim__base_8py.html", "test__twodim__base_8py" ],
    [ "test_type_check.py", "test__type__check_8py.html", "test__type__check_8py" ],
    [ "test_ufunclike.py", "test__ufunclike_8py.html", "test__ufunclike_8py" ],
    [ "test_utils.py", "lib_2tests_2test__utils_8py.html", "lib_2tests_2test__utils_8py" ]
];