var dir_8e8909a0184c917beee6d27ee02ed6b6 =
[
    [ "include", "dir_53455464bfedfbb18c9eb2121f0f2ee1.html", "dir_53455464bfedfbb18c9eb2121f0f2ee1" ],
    [ "tests", "dir_48760b6d126acf8ccda7f0b51d7f37ae.html", "dir_48760b6d126acf8ccda7f0b51d7f37ae" ],
    [ "__init__.py", "core_2____init_____8py.html", "core_2____init_____8py" ],
    [ "_dummy.py", "__dummy_8py.html", "__dummy_8py" ],
    [ "_internal.py", "__internal_8py.html", "__internal_8py" ],
    [ "_methods.py", "__methods_8py.html", "__methods_8py" ],
    [ "_multiarray_tests.py", "__multiarray__tests_8py.html", "__multiarray__tests_8py" ],
    [ "_operand_flag_tests.py", "__operand__flag__tests_8py.html", "__operand__flag__tests_8py" ],
    [ "_rational_tests.py", "__rational__tests_8py.html", "__rational__tests_8py" ],
    [ "_struct_ufunc_tests.py", "__struct__ufunc__tests_8py.html", "__struct__ufunc__tests_8py" ],
    [ "_umath_tests.py", "__umath__tests_8py.html", "__umath__tests_8py" ],
    [ "arrayprint.py", "arrayprint_8py.html", "arrayprint_8py" ],
    [ "cversions.py", "cversions_8py.html", "cversions_8py" ],
    [ "defchararray.py", "defchararray_8py.html", "defchararray_8py" ],
    [ "einsumfunc.py", "einsumfunc_8py.html", "einsumfunc_8py" ],
    [ "fromnumeric.py", "fromnumeric_8py.html", "fromnumeric_8py" ],
    [ "function_base.py", "core_2function__base_8py.html", "core_2function__base_8py" ],
    [ "generate_numpy_api.py", "generate__numpy__api_8py.html", "generate__numpy__api_8py" ],
    [ "getlimits.py", "getlimits_8py.html", "getlimits_8py" ],
    [ "info.py", "core_2info_8py.html", "core_2info_8py" ],
    [ "machar.py", "machar_8py.html", "machar_8py" ],
    [ "memmap.py", "memmap_8py.html", "memmap_8py" ],
    [ "multiarray.py", "multiarray_8py.html", "multiarray_8py" ],
    [ "numeric.py", "numeric_8py.html", "numeric_8py" ],
    [ "numerictypes.py", "numerictypes_8py.html", "numerictypes_8py" ],
    [ "records.py", "records_8py.html", "records_8py" ],
    [ "setup.py", "core_2setup_8py.html", "core_2setup_8py" ],
    [ "setup_common.py", "setup__common_8py.html", "setup__common_8py" ],
    [ "shape_base.py", "core_2shape__base_8py.html", "core_2shape__base_8py" ],
    [ "umath.py", "umath_8py.html", "umath_8py" ],
    [ "umath_tests.py", "umath__tests_8py.html", "umath__tests_8py" ]
];